MVCExercise/Models/Category.cs
namespace MVCExercise.Models;

public class Category
{
    public int CategoryID { get; set; }
    public string Name { get; set; }    
}

MVCExercise/Models/ErrorViewModel.cs
namespace MVCExercise.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

MVCExercise/Models/Product.cs
namespace MVCExercise.Models;

public class Product
{
    public int ProductID { get; set; }
    public string Name { get; set; }
    public double Price { get; set; }
    public int CategoryID { get; set; }
    public bool OnSale { get; set; }
    public int StockLevel { get; set; } 
    public IEnumerable<Category> Categories { get; set; }
}

MVCExercise/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using MVCExercise.Models;

namespace MVCExercise.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

MVCExercise/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using MVCExercise.Data;
using MVCExercise.Models;

namespace MVCExercise.Controllers;

public class ProductController : Controller
{
    private readonly IProductRepository _repository;

    public ProductController(IProductRepository repository)
    {
        _repository = repository;
    }
    // GET
    public IActionResult Index()
    {
        var products = _repository.GetAllProducts();
        return View(products);
    }

    public IActionResult ViewProduct(int id)
    {
        var product = _repository.GetProduct(id);
        return View(product);
    }

    public IActionResult UpdateProduct(int id)
    {
        var product = _repository.GetProduct(id);
        if (product == null)
        {
            return View("ProductNotFound");
        }

        return View(product);
    }
    public IActionResult UpdateProductToDatabase(Product product)
    {
        _repository.UpdateProduct(product);

        return RedirectToAction("ViewProduct", new { id = product.ProductID });
    }
    public IActionResult InsertProduct()
    {
        var prod = _repository.AssignCategory();
        return View(prod);
    }
    
    public IActionResult InsertProductToDatabase(Product productToInsert)
    {
        _repository.InsertProduct(productToInsert);
        return RedirectToAction("Index");
    }
    
    public IActionResult DeleteProduct(Product product)
    {
        _repository.DeleteProduct(product);
        return RedirectToAction("Index");
    }
}

MVCExercise/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MVCExercise/Views/Product/Index.cshtml
@using System.Reflection
@model IEnumerable<Product>

<h2>Products</h2>

<div style="display: block">
    <a href="/Product/InsertProduct/">Create a New Product</a>
</div>

<table class="table">
   
    <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Price</th>
        <th>Category ID</th>
        <th>Sale</th>
        <th>Stock</th>
    </tr>
    
   @foreach (var product in @Model)
    {
        <tr>
            <td><a href="Product/ViewProduct/@product.ProductID">@product.ProductID</a></td>
            <td>@product.Name</td>
            <td>@product.Price</td>
            <td>@product.CategoryID</td>
            <td>@product.OnSale</td>
            <td>@product.StockLevel</td>
        </tr>
    }
</table>

MVCExercise/Views/Product/InsertProduct.cshtml
@model Product

<h2>Create a New Product</h2>

@using (Html.BeginForm("InsertProductToDatabase", "Product", "Post"))
{
    <input asp-for="ProductID" type="hidden" value="" />

    <label asp-for="Name" class="control-label">Name</label>
    <input type="text" name="Name" class="form-control" value="" />

    <label asp-for="Price" class="control-label">Price</label>
    <input type="number" step="0.01" name="Price" class="form-control" />

    <div class="form-group">
        <label for="">Select a Category</label>
        <select class="form-control" name="CategoryID" value="">
            @foreach (var cat in Model.Categories)
            {
                <option value="@cat.CategoryID">@cat.CategoryID @cat.Name</option>
            }
        </select>
    </div>
    
    <input type="submit" value="Create Product" class="btn btn-primary" />
}

MVCExercise/Views/Product/UpdateProduct.cshtml
@model Product

<h2>Update @Model.Name</h2>

@using (Html.BeginForm("UpdateProductToDatabase", "Product", "Post"))
{
    <input asp-for="ProductID" type="hidden" value="@Model.ProductID" />

    <label asp-for="Name" class="control-label">Name</label>
    <input type="text" name="Name" class="form-control" value="@Model.Name" />

    <label asp-for="Price" class="control-label">Price</label>
    <input type="number" step="0.01" name="Price" class="form-control" value="@Model.Price" />

    <input type="submit" value="Update Product" class="btn btn-primary" />
}

MVCExercise/Views/Product/ViewProduct.cshtml
@model Product

<h2>@Model.Name Information</h2>

<table class="table">
    <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Price</th>
        <th>CategoryID</th>
        <th>Sale</th>
        <th>Stock</th>
    </tr>
    
    <tr>
        <td>@Model.ProductID</td>
        <td>@Model.Name</td>
        <td>@Model.Price</td>
        <td>@Model.CategoryID</td>
        <td>@Model.OnSale</td>
        <td>@Model.StockLevel</td>
    </tr>
</table>

<div style="display: block">
    <a href="/Product/UpdateProduct/@Model.ProductID">Update this Product</a>
</div>

<div style="display: block">

    @using (Html.BeginForm("DeleteProduct", "Product", "Post"))
    {
        <input type="hidden" asp-for="ProductID" value="@Model.ProductID" />
        <input type="submit" onclick="return confirm('Are you sure?')" value="Delete this product" />
    }
</div>

MVCExercise/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - MVCExercise</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/MVCExercise.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MVCExercise</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Products</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2024 - MVCExercise - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>